/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jwks */
        get: operations["jwks__well_known_jwks_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Project */
        post: operations["create_project_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Organization
         * @description Bootstrap path: create an organization and make the caller a member.
         *
         *     The caller must not already belong to an organization (by claim or by
         *     membership), or the request is rejected (an identity belongs to one org at
         *     a time in Phase 1).
         */
        post: operations["create_organization_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Product */
        post: operations["create_product_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateOrganizationRequest */
        CreateOrganizationRequest: {
            /** Name */
            name: string;
        };
        /** CreateProductRequest */
        CreateProductRequest: {
            /** Project Id */
            project_id: string;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
        };
        /**
         * Problem
         * @description RFC 9457 problem-details envelope, declared in the OpenAPI schema.
         */
        Problem: {
            /**
             * Type
             * @description Stable problem type identifier (urn:avd:problem:...)
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary
             */
            title: string;
            /**
             * Status
             * @description HTTP status code
             */
            status: number;
            /**
             * Detail
             * @description Human-readable explanation specific to this occurrence
             */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    jwks__well_known_jwks_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_project_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC 9457 problem-details error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_project_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC 9457 problem-details error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_organization_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC 9457 problem-details error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_product_v1_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | number;
                    };
                };
            };
            /** @description RFC 9457 problem-details error */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description RFC 9457 problem-details error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Type
                         * @description Stable problem type identifier (urn:avd:problem:...)
                         */
                        type: string;
                        /**
                         * Title
                         * @description Short, human-readable summary
                         */
                        title: string;
                        /**
                         * Status
                         * @description HTTP status code
                         */
                        status: number;
                        /**
                         * Detail
                         * @description Human-readable explanation specific to this occurrence
                         */
                        detail: string;
                    };
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
